# Generated by Django 5.0.4 on 2024-04-29 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("datamanagement", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyDataModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("domain", models.CharField(max_length=100)),
                ("year_founded", models.IntegerField()),
                ("industry", models.CharField(max_length=100)),
                ("size_range", models.IntegerField()),
                ("locality", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=100)),
                ("linkedin_url", models.CharField(max_length=200)),
                ("current_employee_estimate", models.IntegerField()),
                ("total_employee_estimate", models.IntegerField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
